### ISSUE TITLE
QUnit bug

### ISSUE THREAD

**Issue by H1D** [ember-cli/ember-twiddle#476] opened 2016-09-08 08:22 UTC
Did single thing on empty twiddle: created unit test for app controller. Now getting this error in console:
`Cannot set property QUnitAdapter of #<Object> which has only a getter`
example: https://ember-twiddle.com/52b66df6f8b8505381d632df01ab6eaf?openFiles=tests.unit.controllers.application.js%2C

To reproduce:
1) create new twiddle
2) generate unit test controller from menu

**Comment by rwjblue** [comment] 2016-09-08 11:47
Closing as a duplicate of https://github.com/ember-cli/ember-twiddle/issues/468

**Closed by rwjblue** 2016-09-08 11:47 UTC
