### ISSUE TITLE
Component integration tests broken

### ISSUE THREAD

**Issue by san650** [ember-cli/ember-twiddle#468] opened 2016-07-29 16:58 UTC
When trying to create a new component integration tests I'm getting the following errors:

![screen shot 2016-07-29 at 1 50 13 pm](https://cloud.githubusercontent.com/assets/1234607/17256553/68800928-5594-11e6-9fe4-4716530a3470.png)

The files are generated correctly but twiddle doesn't enable testing mode so I can't run the tests.

Tested on Google Chrome  51.0.2704.103 (64-bit) and Safari 9.1.2 (11601.7.7)

**Comment by alexlafroscia** [comment] 2016-07-29 21:37
I'm seeing the same thing; the box that should show the test results just comes up blank, and I'm seeing the same errors in the console.

**Comment by Gaurav0** [comment] 2016-08-01 09:45
Thanks for reporting. This is some kind of breaking change with Ember 2.7. Set the ember version to 2.6.2 as a workaround while I try to fix this.

**Comment by rwjblue** [comment] 2016-08-01 13:12
@Gaurav0 - Please let me know what you find out when you dig into it.

**Comment by Gaurav0** [comment] 2016-08-01 19:40
@rwjblue What I've discovered so far:

Locally, works using ember serve
Locally, reproduces problem with ember serve --environment=production
Locally, reproduces problem with ember serve --environment=production with minification turned off

The error is:

`VM197 test-support.js?0.10.5+fa6caa98:1 Uncaught TypeError: Cannot set property QUnitAdapter of #<Object> which has only a getter`

Looking at source code, in Ember 2.6.2, https://github.com/emberjs/ember.js/blob/v2.6.2/packages/ember-testing/lib/index.js#L19'

`Ember.Test.QUnitAdapter = QUnitAdapter;`

In Ember 2.7.0,
https://github.com/emberjs/ember.js/blob/v2.7.0/packages/ember-testing/lib/index.js#L21-L23

```
Object.defineProperty(Test, 'QUnitAdapter', {
  get: () => require('ember-testing/adapters/qunit').default
});
```

it appears QUnitAdapter was made read only without any deprecation warning in PR https://github.com/emberjs/ember.js/pull/13440

**Comment by rwjblue** [comment] 2016-08-01 21:01
When/why are we setting `Ember.Test.QUnitAdapter` in ember-twiddle's codebase?

**Comment by rwjblue** [comment] 2016-08-01 21:02
Is it possible that we are using the version of `bower_components/ember/ember-testing.js` that comes with whatever version of Ember that ember-twiddle.com itself is running instead of the one being ran inside the specific twiddle?

**Comment by Gaurav0** [comment] 2016-08-01 21:09
> When/why are we setting Ember.Test.QUnitAdapter in ember-twiddle's codebase?

It seems to be coming from test-support.js

> Is it possible that we are using the version of bower_components/ember/ember-testing.js that comes with whatever version of Ember that ember-twiddle.com itself is running instead of the one being ran inside the specific twiddle?

Yes. Fixing this may be the solution.

**Comment by rwjblue** [comment] 2016-08-01 21:12
Mixing various assets from different versions of Ember will always have a problem. We definitely do not support the idea that you can use mismatched versions of `ember.debug.js` and `ember-testing.js` or `ember.debug.js` and `ember-template-compiler.js`.  The Ember assets loaded must be from the same build.

**Comment by Gaurav0** [comment] 2016-08-01 21:12
Yes. Definitely an oversight.

**Comment by rwjblue** [comment] 2016-08-01 21:13
When things settle down a bit with the Glimmer alpha I'll try to ensure that loading `ember-testing.js` checks to ensure it is being integrated with the same version (or something like that) and provide a helpful assertion.

It is an easy mistake to make (one that I have done many times).

**Comment by Gaurav0** [comment] 2016-08-02 01:02
Not sure if it is just that the cache failed to bust or if the issue is not fixed. @joostdevries Can you check? test-support.js does not seem to have been updated on canary.

**Comment by Gaurav0** [comment] 2016-08-02 18:29
The cache indeed failed to bust. I'm going to have to fingerprint all the files and in some way still dynamically generate the links in js.

**Comment by Gaurav0** [comment] 2016-10-13 20:48
Fixed in canary.

**Closed by Gaurav0** 2016-10-13 20:48 UTC
