### ISSUE TITLE
Remove hyphen restriction when creating template-only component

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-twiddle#724] opened 2020-06-13 22:45 UTC
Just noticed when creating a template only component that it still wants a hyphen. 

I just tried naming the component "Link"

**Comment by Gaurav0** [comment] 2020-06-15 17:16
This shouldn't be happening if you are using a newly generated twiddle.json. The behavior is on only for backward compatibility with old twiddles. Can you give me a link to a twiddle which is not working?

**Comment by NullVoxPopuli** [comment] 2020-06-15 17:23
https://ember-twiddle.com/5a3fa797b26e8807869340792219a5ee?openFiles=components.demo%5C.hbs%2Ccomponents.demo%5C.hbs

**Comment by Gaurav0** [comment] 2020-06-15 18:54
Unable to reproduce in this twiddle. See https://ember-twiddle.com/d3eb4ea4ef225e048c1ad77e7a51cf77?openFiles=components.link%5C.js%2Ctemplates.components.link%5C.hbs

**Comment by NullVoxPopuli** [comment] 2020-06-16 00:41
do this:

![image](https://user-images.githubusercontent.com/199018/84719149-92958500-af48-11ea-86ba-5f68708607e5.png)

**Comment by Gaurav0** [comment] 2020-06-18 17:56
Fixed on https://canary.ember-twiddle.com by https://github.com/ember-cli/ember-twiddle/commit/812a414528ae3dd3694edfbf0d74002337610eda

**Closed by Gaurav0** 2020-06-18 17:56 UTC
